# Generated by Django 5.1.4 on 2025-01-13 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('age', models.PositiveSmallIntegerField(default=18)),
                ('nationality', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('athlete', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport_records.athlete')),
            ],
        ),
    ]
